name: arkbreeder-dev
channels:
  - conda-forge
dependencies:
  - python >=3.9.1
  - pip

    # Base
  - pydantic >=1.7.3,<2.0.0a
  - sqlalchemy ==1.3 
  - dash ==1.19
  - tqdm

    # Testing
  - pytest
  - pytest-cov

    # Lint
  - autoflake
  - black
  - isort
  - mypy

  - pip:
    - pydantic_sqlalchemy ==0.0.8
  
  
